// Global variable to store the full list of modules
let allModules = [];
let moduleListContainer;  // Global reference to the module container
const selectedModulesSet = new Set(); //  To keep the selection persistent

// Wait until the document is ready
$(document).ready(function () {
  $('#batch_connect_session_context_selected_modules').val('');
  $('#batch_connect_session_context_module_filter').val('');

  // Bind input event to the module filter
  $('#batch_connect_session_context_module_filter').on('input', function () {
    updateFilteredModules(); // Called when the user types
  });

  // Select the input generated by module_list
  const moduleListInput = $('#module_list_container');
  if (moduleListInput.length > 0) {
    moduleListContainer = createModuleListContainer();
    moduleListInput.replaceWith(moduleListContainer);

    // Load modules
    // The host needs to be changed to the machine that's serving the module list
    $.ajax({
      url: 'https://10.3.3.59:5000/modules',
      type: 'GET',
      success: function (response) {
        if (response.success && response.modules && response.modules.length > 0) {
          allModules = response.modules;
          renderModuleList(allModules); // Show all on load
        }
      }
    });

    // Change event
    $(document).on('change', 'input[name="modules"]', function () {
      const moduleName = $(this).val();
      if ($(this).is(':checked')) {
        selectedModulesSet.add(moduleName);
      } else {
        selectedModulesSet.delete(moduleName);
      }
      // Update hidden field
      $('#batch_connect_session_context_selected_modules').val(Array.from(selectedModulesSet).join(' '));
    });
  }
});

// Render modules while respecting the previous selection
function renderModuleList(modules) {
  moduleListContainer.empty();
  modules.forEach((module) => {
    const isChecked = selectedModulesSet.has(module) ? 'checked' : '';
    const moduleElement = `
      <div>
        <input type="checkbox" id="module_${module}" name="modules" value="${module}" ${isChecked}>
        <label for="module_${module}">${module}</label>
      </div>
    `;
    moduleListContainer.append(moduleElement);
  });
}

// Dynamic filter
function updateFilteredModules() {
  const filterText = $('#batch_connect_session_context_module_filter').val().toLowerCase().trim();
  if (filterText === '') {
    renderModuleList(allModules); // Show all if the filter is empty
  } else {
    const filteredModules = allModules.filter((module) =>
      module.toLowerCase().includes(filterText)
    );
    renderModuleList(filteredModules);
  }
}

// Create container
function createModuleListContainer() {
  return $('<div>', {
    id: 'module_list_container',
    style: `
      background: none;
      border: 1px solid #ccc;
      padding: 10px;
      margin-top: 1em;
      margin-bottom: 16px;
      height: 200px;
      overflow-y: auto;
    `,
  });
}
